services:
  mongo:
    build: ./dev/mongo/
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
  
  apache_php:
    build: ./dev/php/
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mongo
    restart: unless-stopped

  mongoseed:
    build: ./dev/mongoseed/
    links:
      - mongo
    volumes:
      - ./mongoseed:/mongoseed
    restart: "no"
    command: mongoimport --host mongo --db exploit --collection users --type json --file /tmp/users.json --jsonArray
